export const DIR_VIEWS = "views"
export const DIR_CSS = "css"
export const DIR_JS = "js"

export const FILE_BACKGROUND_JS = "background.js"
export const FILE_POPUP = DIR_VIEWS + "/popup.html"
export const FILE_OPTIONS = DIR_VIEWS + "/options.html"
export const FILE_POPUP_JS = DIR_JS + "/popup.js"
export const FILE_POPUP_CSS = DIR_CSS + "/popup.css"
export const FILE_CONTENT_JS = DIR_JS + "/content.js"
export const FILE_CONTENT_CSS = DIR_CSS + "/content.css"
export const FILE_OPTIONS_JS = DIR_JS + "/options.js"
export const FILE_OPTIONS_CSS = DIR_CSS + "/options.css"
